<a href="https://colab.research.google.com/github/Umarsmuhammed/Arewa_DeepLearning/blob/main/Week_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Documentation reading**
- The documentation on torch.Tensor.
- The documentation on torch.cuda.

In [4]:
# No code solution (reading)

**2. Create a random tensor with shape (7, 7).**

In [5]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.9800, 0.8143, 0.0296, 0.4325, 0.1742, 0.4233, 0.4268],
         [0.6644, 0.7338, 0.5288, 0.8744, 0.2956, 0.4091, 0.7743],
         [0.3500, 0.9096, 0.8096, 0.9412, 0.8179, 0.2849, 0.6034],
         [0.7487, 0.5929, 0.5917, 0.1743, 0.5703, 0.6446, 0.9783],
         [0.7100, 0.8702, 0.2271, 0.0219, 0.5806, 0.0170, 0.2643],
         [0.5194, 0.7237, 0.0337, 0.0946, 0.4267, 0.7260, 0.0247],
         [0.3191, 0.2693, 0.4433, 0.6789, 0.1202, 0.2498, 0.4546]]),
 torch.Size([7, 7]))

**3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [6]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[2.1698],
         [2.6218],
         [2.6760],
         [2.8541],
         [1.7131],
         [1.7237],
         [1.4953]]),
 torch.Size([7, 1]))

**4. Set the random seed to 0 and do 2 & 3 over again.**

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

**5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)**
- If there is, set the GPU random seed to 1234.

In [8]:
# Set random seed

torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

Device: cpu


**6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

**7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**

In [10]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

**8. Find the maximum and minimum values of the output of 7.**

In [11]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min


(tensor(0.5617), tensor(0.3647))

**9. Find the maximum and minimum index values of the output of 7.**

In [12]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3), tensor(0))

**10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
